plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.95'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-neoforge1.21.1"
}

repositories {
    mavenCentral()
    maven { url = 'https://api.modrinth.com/maven' }
    maven { url = 'https://cursemaven.com' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    mavenLocal()
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    implementation "maven.modrinth:epic-fight:${project.epicfight_version}"
    implementation "software.bernie.geckolib:geckolib-neoforge-1.21.1:${project.geckolib_version}"

    implementation files('libs/invincible-21.15.8.1-mc1.21.1-neoforge.jar')
    implementation files('libs/epic_fight_avalon-neoforge1.21.1-21.12.6.3.jar')

    compileOnly files('libs/aaa_particles-neoforge-1.21.1-2.2.0.jar')
    compileOnly files('libs/smartkeyprompts-neoforge-1.21.1-1.1.3.jar')
    compileOnly 'curse.maven:epic-fight-skill-tree-1295882:7304009'
    compileOnly files('libs/guhaos-vix-1531111-8258354.jar')

    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

tasks.named('jar', Jar).configure {
    from(zipTree(layout.projectDirectory.file('libs/guhaos-vix-1531111-8258354.jar'))) {
        exclude 'META-INF/**'
        exclude 'vix.mixins.json'
        exclude 'pack.mcmeta'
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
