package com.hm.efn.registries;

import com.hm.efn.mobeffects.AttackDamageIncreaseEffect;
import com.hm.efn.mobeffects.AttackSpeedIncreaseEffect;
import com.hm.efn.mobeffects.BattleContinuationEffect;
import com.hm.efn.mobeffects.BloodBlessingsEffect;
import com.hm.efn.mobeffects.BloodExplosionEffect;
import com.hm.efn.mobeffects.BloodlustEnhance;
import com.hm.efn.mobeffects.BreathingRing;
import com.hm.efn.mobeffects.BypassDodgeEffect;
import com.hm.efn.mobeffects.ClawEnhance;
import com.hm.efn.mobeffects.ComboExecuteWindow;
import com.hm.efn.mobeffects.CurseOfBloodEffect;
import com.hm.efn.mobeffects.DamageReductionEffect;
import com.hm.efn.mobeffects.DieMarkEffect;
import com.hm.efn.mobeffects.FalchionBless;
import com.hm.efn.mobeffects.FalchionVulnerability;
import com.hm.efn.mobeffects.GradualHeal;
import com.hm.efn.mobeffects.GuardPunctureEffect;
import com.hm.efn.mobeffects.HeavyRainStunEffect;
import com.hm.efn.mobeffects.HorizontalStop;
import com.hm.efn.mobeffects.InvincibilityEffect;
import com.hm.efn.mobeffects.KnockBackResistanceEffect;
import com.hm.efn.mobeffects.MeenLance;
import com.hm.efn.mobeffects.MurasamaSheathEffect;
import com.hm.efn.mobeffects.Replay;
import com.hm.efn.mobeffects.Shiver;
import com.hm.efn.mobeffects.SinStunImmunity;
import com.hm.efn.mobeffects.StopEffect;
import com.hm.efn.mobeffects.StunEffect;
import com.hm.efn.mobeffects.VerticalStop;
import com.hm.efn.mobeffects.VulnerabilityEffect;
import com.hm.efn.mobeffects.Yamato;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.effect.MobEffect;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class EFNMobEffectRegistry {
   public static final DeferredRegister<MobEffect> EFFECTS = DeferredRegister.create(Registries.MOB_EFFECT, "efn");
   public static final DeferredHolder<MobEffect, MobEffect> SIN_STUN_IMMUNITY = EFFECTS.register("sin_stun_immunity", SinStunImmunity.SinStunImmunityEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> BATTLE_CONTINUATION = EFFECTS.register("battle_continuation", BattleContinuationEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> DIE = EFFECTS.register("die", DieMarkEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> GUARD_PUNCTURE_EFFECT = EFFECTS.register("guard_puncture_effect", GuardPunctureEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> BYPASS_DODGE_EFFECT = EFFECTS.register("bypass_dodge_effect", BypassDodgeEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> MEEN_LANCE = EFFECTS.register("meenlance", MeenLance.MeenLanceEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> YAMATO = EFFECTS.register("yamato", Yamato.YamatoEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> INVINCIBILITY_EFFECT = EFFECTS.register("invincibility", InvincibilityEffect.InvincibilityMobEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> BLODDLUST = EFFECTS.register("bloodlust", BloodlustEnhance.BloodlustEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> CLAW = EFFECTS.register("claw", ClawEnhance.ClawEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> RING = EFFECTS.register("ring", BreathingRing::new);
   public static final DeferredHolder<MobEffect, MobEffect> COMBO_EXECUTE_WINDOW = EFFECTS.register("combo_execute_window", ComboExecuteWindow::new);
   public static final DeferredHolder<MobEffect, MobEffect> REPLAY = EFFECTS.register("replay", Replay::new);
   public static final DeferredHolder<MobEffect, MobEffect> FALCHION_BLESS = EFFECTS.register("falchion_bless", FalchionBless::new);
   public static final DeferredHolder<MobEffect, MobEffect> GRADUAL_HEAL = EFFECTS.register("gradual_heal", GradualHeal::new);
   public static final DeferredHolder<MobEffect, MobEffect> FALCHION_VULNERABILITY = EFFECTS.register("falchion_vulnerability", VulnerabilityEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> SHIVER = EFFECTS.register("shiver", Shiver::new);
   public static final DeferredHolder<MobEffect, MobEffect> KNOCKBACKRESISTANT = EFFECTS.register("knockbackresistant", KnockBackResistanceEffect.ResistanceEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> VERTICALSTOP = EFFECTS.register("verticalstop", VerticalStop::new);
   public static final DeferredHolder<MobEffect, MobEffect> HORIZONTAL_STOP = EFFECTS.register("horizontalstop", HorizontalStop::new);
   public static final DeferredHolder<MobEffect, MobEffect> STUN = EFFECTS.register("yamato_stun", StunEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> HEAVY_RAIN_STUN = EFFECTS.register("heavy_rain_stun", HeavyRainStunEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> VULNERABILITY = EFFECTS.register("vulnerability", VulnerabilityEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> STOP = EFFECTS.register("stop", StopEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> BLOOD_EXPLOSION = EFFECTS.register("blood_explosion", BloodExplosionEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> CURSE_OF_BLOOD = EFFECTS.register("curse_of_blood", CurseOfBloodEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> BLOOD_BLESSINGS = EFFECTS.register("blood_blessing", BloodBlessingsEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> DAMAGE_REDUCTION = EFFECTS.register("damage_reduction", DamageReductionEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> ATTACK_DAMAGE_INCREASE = EFFECTS.register("attack_damage_increase", AttackDamageIncreaseEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> ATTACK_SPEED_INCREASE = EFFECTS.register("attack_speed_increase", AttackSpeedIncreaseEffect::new);
   public static final DeferredHolder<MobEffect, MobEffect> MURASAMA_SHEATH = EFFECTS.register("murasama_sheath", MurasamaSheathEffect::new);
}
